(()=>{
  "use strict";
  const $=id=>document.getElementById(id);
  const OUR_INSTITUTION="고려저축은행";
  const SUPPORT_RADIUS_PP=.15;
  const MARKET_CONFIG={version:"public-structural-v2-market-position-v1",rate_normalization_decimals:4,counterfactual:"replace_anchor_product",top10_share:.10,top25_share:.25,crowding_windows_pp:[.05,.10]};
  let tablePromise=null,mode="rate",renderToken=0;

  const finite=value=>{if(value===null||value===undefined||String(value).trim()==="")return null;const n=Number(value);return Number.isFinite(n)?n:null};
  const esc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const pct=value=>Number.isFinite(value)?`${Number(value).toFixed(2)}%`:"—";
  const amount=value=>Number.isFinite(value)?`${Number(value).toLocaleString("ko-KR",{maximumFractionDigits:1})}억원`:"—";
  const signed=value=>Number.isFinite(value)?`${value>=0?"+":""}${Number(value).toLocaleString("ko-KR",{maximumFractionDigits:1})}억원`:"—";
  const bp=value=>Number.isFinite(value)?`${value>=0?"+":""}${Math.round(value)}bp`:"—";
  function inlineData(){const node=$("rate-monitor-data");if(!node)throw new Error("rate-monitor-data:missing");return JSON.parse(String(node.textContent||"").replace(/<\\\//g,"</"));}
  function decode(table,column,value){const lookup=table.lookups?.[column];return lookup&&value!==null&&value!==undefined?lookup[value]:value;}
  function decodedRows(table){const columns=table.columns||[],index=Object.fromEntries(columns.map((name,i)=>[name,i]));const get=(row,name)=>name in index?decode(table,name,row[index[name]]):null;return(table.rows||[]).map(row=>({sector:get(row,"sector"),product_type:get(row,"product_type"),term_months:Number(get(row,"term_months")),max_rate:finite(get(row,"max_rate")),product_id:String(get(row,"product_id")??""),institution:String(get(row,"institution")??""),product:String(get(row,"product")??""),source_effective_at:String(get(row,"source_effective_at")??"")}));}
  async function loadTable(){if(tablePromise)return tablePromise;const url=inlineData().table_url;if(!url)throw new Error("strategy-table:url_missing");tablePromise=fetch(url,{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error(`strategy-table:http_${r.status}`);return r.json();}).then(decodedRows);return tablePromise;}
  function activeSectors(){const mutual=[...document.querySelectorAll("[data-sector]:checked")].map(el=>el.dataset.sector).filter(Boolean),selected=document.querySelector("[data-market-mode].active")?.dataset.marketMode||"savings_bank";if(selected==="savings_bank")return["savings_bank"];if(selected==="mutual_finance")return mutual;return["savings_bank",...mutual];}
  const selectedTerm=()=>Number(document.querySelector("#term-segment button.active")?.dataset.term||12);
  function aggregate(rows,term,sectors){const allowed=new Set(sectors),map=new Map();for(const row of rows){if(!allowed.has(row.sector)||row.product_type!=="term_deposit"||row.term_months!==term||row.max_rate===null||!row.product_id)continue;const key=`${row.sector}\0${row.product_id}\0${term}`,old=map.get(key);if(!old||row.max_rate>old.max_rate||(row.max_rate===old.max_rate&&row.source_effective_at>old.source_effective_at))map.set(key,row);}return[...map.values()].sort((a,b)=>b.max_rate-a.max_rate||a.institution.localeCompare(b.institution,"ko")||a.product.localeCompare(b.product,"ko"));}
  function marketContext(rows){const term=selectedTerm(),sectors=activeSectors(),products=aggregate(rows,term,sectors),anchor=products.filter(row=>row.sector==="savings_bank"&&row.institution===OUR_INSTITUTION).sort((a,b)=>b.max_rate-a.max_rate||a.product_id.localeCompare(b.product_id))[0];if(!anchor)throw new Error("현재 선택 범위에서 고려저축은행 기준상품을 찾지 못했습니다.");return{term,products,anchor,anchorId:`${anchor.sector}:${anchor.product_id}`,marketRows:products.map(row=>({product_id:`${row.sector}:${row.product_id}`,rate:row.max_rate}))};}
  function scenarioInputs(){return{baseline_new_money:finite($("baseline-new")?.value),maturity_amount:finite($("maturity-amount")?.value),current_rollover_rate_pct:finite($("rollover-rate")?.value)};}
  const hasScenarioInputs=inputs=>Object.values(inputs).every(value=>value!==null);
  function canonicalProposal(){const base=finite($("base-n")?.value),bonus=finite($("bonus-n")?.value);return base===null||bonus===null?null:Number((base+bonus).toFixed(4));}
  function buildSurface(context,proposal,inputs){const data=inlineData(),config=data.strategy?.inflow_prediction;if(!config?.scenarios?.length)throw new Error("Public Structural inflow config가 없습니다.");return PublicStructuralV2Surface.buildSurface({generated_at:data.generated_at||new Date().toISOString(),market_rows:context.marketRows,anchor_product_id:context.anchorId,current_own_rate:context.anchor.max_rate,proposal_rate:proposal,economics_min_rate:Math.max(0,Number((context.anchor.max_rate-SUPPORT_RADIUS_PP).toFixed(4))),economics_max_rate:Number((context.anchor.max_rate+SUPPORT_RADIUS_PP).toFixed(4)),baseline_new_money:inputs.baseline_new_money,maturity_amount:inputs.maturity_amount,current_rollover_rate_pct:inputs.current_rollover_rate_pct,term_months:context.term},PublicStructuralV2MarketPosition,MARKET_CONFIG,PublicStructuralV2DecisionContract,PublicStructuralV2Inflow,config);}
  function positionFor(context,rate){return PublicStructuralV2MarketPosition.marketPosition({rows:context.marketRows,anchor_product_id:context.anchorId,current_own_rate:context.anchor.max_rate,proposal_rate:rate},MARKET_CONFIG);}
  const forecastAt=(surface,rate)=>(surface.forecast?.scenarios||[]).find(row=>Math.abs(Number(row.rate_pct)-rate)<.00005)||null;
  const positionAt=(surface,rate)=>(surface.market_positions||[]).find(row=>Math.abs(Number(row.proposal_rate)-rate)<.00005)||null;
  function rankText(position){if(!position)return"—";return position.rank_best===position.rank_worst?`${position.rank_best}위 / ${position.universe_count}개`:`${position.rank_best}~${position.rank_worst}위 / ${position.universe_count}개`;}
  function nearbyHtml(context,review){const rows=context.products.map(row=>({...row,gapBp:(row.max_rate-review)*100,absGapBp:Math.abs((row.max_rate-review)*100)})).filter(row=>row.absGapBp<=10.0001).sort((a,b)=>a.absGapBp-b.absGapBp||b.max_rate-a.max_rate||a.institution.localeCompare(b.institution,"ko"));if(!rows.length)return'<div class="rds-empty">검토금리 ±10bp 안에 현재 비교상품이 없습니다.</div>';return`<div class="rds-table-wrap"><table class="rds-table"><thead><tr><th>금융사</th><th>상품</th><th>최고금리</th><th>검토 대비</th><th>기준일</th></tr></thead><tbody>${rows.slice(0,12).map(row=>`<tr><td>${esc(row.institution)}</td><td>${esc(row.product)}</td><td>${pct(row.max_rate)}</td><td>${bp(row.gapBp)}</td><td>${esc(row.source_effective_at?row.source_effective_at.slice(0,10):"자료없음")}</td></tr>`).join("")}</tbody></table></div>`;}
  function peerHtml(review){const rp=inlineData().strategy?.relative_pricing;if(!rp||rp.status!=="ready"||!Array.isArray(rp.peers)||!rp.peers.length)return'<div class="rds-empty">공식 pricing peer는 Relative Pricing 근거 gate가 통과될 때만 표시합니다.</div>';const peers=rp.peers.map(peer=>({...peer,rate:finite(peer.rate_pct)})).filter(peer=>peer.rate!==null).map(peer=>({...peer,gap:(peer.rate-review)*100})).sort((a,b)=>Math.abs(a.gap)-Math.abs(b.gap)).slice(0,6);return`<div class="rds-table-wrap"><table class="rds-table"><thead><tr><th>기관</th><th>대표금리</th><th>검토 대비</th><th>수신잔액</th><th>6M 변화</th></tr></thead><tbody>${peers.map(peer=>`<tr><td>${esc(peer.institution||peer.institution_id||"기관 미상")}</td><td>${pct(peer.rate)}</td><td>${bp(peer.gap)}</td><td>${finite(peer.funding_balance_million_krw)===null?"자료없음":`${Number(peer.funding_balance_million_krw).toLocaleString("ko-KR",{maximumFractionDigits:0})}백만원`}</td><td>${finite(peer.funding_change_6m_pct)===null?"자료없음":`${Number(peer.funding_change_6m_pct).toFixed(1)}%`}</td></tr>`).join("")}</tbody></table></div>`;}
  function shell(){return`<div class="rds-head"><div><h3>금리결정 시뮬레이터</h3><p>검토금리 또는 목표 수신액을 기준으로 시장 위치·경쟁사·미보정 수신 시나리오를 비교합니다.</p></div><span class="rds-safety">내부 실적 미보정 · 구조 시나리오</span></div><div class="rds-tabs"><button class="rds-tab active" data-rds-mode="rate" type="button">금리로 계산</button><button class="rds-tab" data-rds-mode="target" type="button">목표금액으로 찾기</button></div><div class="rds-controls"><label class="rds-rate-mode">검토금리 <input id="rds-review-rate" type="number" step="0.01" min="0" max="15"> %</label><label class="rds-target-mode" hidden>목표 총수신 <input id="rds-target-total" type="number" step="1" min="0"> 억원</label></div><div class="rds-metrics"><div><span>검토금리</span><b id="rds-rate">—</b><small id="rds-rate-note">입력 확인 중</small></div><div><span>예상 총수신 · 구조 시나리오</span><b id="rds-total">—</b><small id="rds-range">입력 확인 중</small></div><div><span>현재 대비</span><b id="rds-delta">—</b></div><div><span>시장 위치</span><b id="rds-rank">—</b><small id="rds-threshold">—</small></div></div><div class="rds-grid"><section><h4>현재 이 금리 주변 경쟁상품</h4><div id="rds-nearby"></div></section><section><h4>공식 가격 경쟁기관</h4><div id="rds-peers"></div></section></div><div class="rds-evidence"><div><b>비슷한 급 경쟁사</b><span>수신잔액 + 총자산이 모두 연결되기 전에는 규모 peer를 만들지 않습니다.</span></div><div><b>과거 당사 사례</b><span>당시 시장 snapshot과 상품별 실적 연결 전에는 사례를 추정하지 않습니다.</span></div><div><b>목표금액 해석</b><span>existing candidate finder · 보간/외삽/자동 최적화 아님</span></div></div><details class="rds-details"><summary>상세 분석 · 후보금리표 / Response Surface / Market Position Ladder</summary><div id="rds-legacy"></div></details>`;}
  function renderFacts(context,rate,surface){const position=positionAt(surface,rate)||positionFor(context,rate),forecast=forecastAt(surface,rate);$("rds-rate").textContent=pct(rate);$("rds-rank").textContent=rankText(position);$("rds-threshold").textContent=`TOP10 ${pct(position.top10_cutoff)} · TOP25 ${pct(position.top25_cutoff)} · 중앙 ${pct(position.median_rate)}`;$("rds-nearby").innerHTML=nearbyHtml(context,rate);$("rds-peers").innerHTML=peerHtml(rate);if(forecast){$("rds-total").textContent=amount(forecast.predicted_total);$("rds-range").textContent=`stress ${amount(forecast.predicted_total_lower)} ~ ${amount(forecast.predicted_total_upper)}`;$("rds-delta").textContent=signed(forecast.incremental_total);}else{$("rds-total").textContent="—";$("rds-range").textContent="해당 금리의 structural candidate가 없습니다.";$("rds-delta").textContent="—";}}
  function moveLegacy(){const legacy=$("rds-legacy"),cockpit=$("public-structural-v2-cockpit"),response=$("rate-response-wrap");if(!legacy)return;if(response&&!legacy.contains(response))legacy.appendChild(response);if(cockpit&&!legacy.contains(cockpit))legacy.appendChild(cockpit);}
  async function render(){const token=++renderToken,host=$("strategy-rate-decision-simulator");if(!host)return;try{const rows=await loadTable();if(token!==renderToken)return;const context=marketContext(rows),inputs=scenarioInputs(),review=finite($("rds-review-rate")?.value)??canonicalProposal()??context.anchor.max_rate;if(!$("rds-review-rate").value)$("rds-review-rate").value=review.toFixed(2);if(!hasScenarioInputs(inputs)){renderFacts(context,review,{forecast:{scenarios:[]},market_positions:[]});$("rds-total").textContent="입력 필요";$("rds-range").textContent="최근 신규수신·만기도래액·재예치율을 입력하세요.";return;}if(mode==="rate"){const surface=buildSurface(context,review,inputs);$("rds-rate-note").textContent="입력한 검토금리";renderFacts(context,review,surface);return;}const target=finite($("rds-target-total")?.value);if(target===null){$("rds-rate").textContent="입력 필요";$("rds-rate-note").textContent="목표 총수신을 입력하세요.";return;}if(typeof StrategyTargetCandidate!=="object")throw new Error("target candidate selector가 없습니다.");const surface=buildSurface(context,context.anchor.max_rate,inputs),selection=StrategyTargetCandidate.findFirstCandidate(surface.forecast?.scenarios||[],target);if(selection.status!=="ready"){$("rds-rate").textContent="범위 밖";$("rds-rate-note").textContent="현재 구조 시나리오 범위에서는 목표금액을 만족하는 금리 후보를 찾을 수 없습니다.";$("rds-total").textContent="—";$("rds-range").textContent=`목표 ${amount(target)}`;$("rds-delta").textContent="—";return;}$("rds-review-rate").value=selection.rate_pct.toFixed(2);$("rds-rate-note").textContent="목표 이상이 되는 첫 후보금리 · 자동 최적화 아님";renderFacts(context,selection.rate_pct,surface);}catch(error){$("rds-rate-note").textContent=`계산 차단 · ${String(error?.message||error)}`;}}
  function install(){const panel=$("prediction-panel");if(!panel||$("strategy-rate-decision-simulator"))return;const host=document.createElement("section");host.id="strategy-rate-decision-simulator";host.className="strategy-rate-decision-simulator";host.innerHTML=shell();const inputs=panel.querySelector(".predict-inputs");(inputs||panel.firstElementChild)?.insertAdjacentElement("afterend",host);host.querySelectorAll("[data-rds-mode]").forEach(button=>button.addEventListener("click",()=>{mode=button.dataset.rdsMode;host.querySelectorAll("[data-rds-mode]").forEach(item=>item.classList.toggle("active",item===button));host.querySelector(".rds-rate-mode").hidden=mode!=="rate";host.querySelector(".rds-target-mode").hidden=mode!=="target";render();}));$("rds-review-rate")?.addEventListener("input",render);$("rds-target-total")?.addEventListener("input",render);["baseline-new","maturity-amount","rollover-rate","base-n","bonus-n"].forEach(id=>$(id)?.addEventListener("change",()=>setTimeout(render,0)));document.querySelectorAll("[data-market-mode],[data-sector],#term-segment button").forEach(el=>el.addEventListener("click",()=>setTimeout(render,50)));setTimeout(moveLegacy,0);new MutationObserver(()=>setTimeout(moveLegacy,0)).observe(panel,{childList:true});render();}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install,{once:true});else install();
})();