# ruff: noqa: E501
"""Strategy 화면에 시장 수신흐름·기관 경쟁·4분면·성장률 랭킹을 주입한다."""

from __future__ import annotations

from rate_monitor.services.dashboard_service import DashboardBuildError

STYLE_MARKER = 'id="market-funding-strategy-style"'
SCRIPT_MARKER = 'id="market-funding-strategy-script"'

_CSS = r"""
<style id="market-funding-strategy-style">
.market-funding{margin:0 0 12px;padding:18px}.market-funding-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:12px}.market-funding-head h2{margin:0;color:var(--ink);font-size:16px;letter-spacing:-.03em}.market-funding-head p{margin:4px 0 0;color:var(--muted);font-size:10.5px;line-height:1.55}.market-funding-badge{flex:0 0 auto;padding:5px 8px;border:1px solid var(--accent-line,rgba(128,200,166,.2));border-radius:999px;background:var(--accent-soft,rgba(128,200,166,.08));color:var(--accent-ink,var(--green));font-size:9.5px;font-weight:760}.funding-market-strip{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-bottom:10px}.funding-market-card{padding:12px;border:1px solid var(--line);border-radius:11px;background:var(--panel2,#FCFAFC)}.funding-market-card span{display:block;color:var(--muted);font-size:9.5px}.funding-market-card b{display:block;margin-top:6px;color:var(--ink);font:760 22px/1 var(--mono)}.funding-market-card b small{font-size:10px;font-weight:650}.funding-market-card em{display:block;margin-top:6px;color:var(--soft);font-size:9.5px;font-style:normal}.funding-market-card em.up{color:var(--green)}.funding-market-card em.down{color:var(--red)}
.funding-sector-tabs{display:flex;gap:5px;flex-wrap:wrap;margin:0 0 10px}.funding-sector-tabs button{border:1px solid var(--line);border-radius:8px;background:var(--panel2,#FBF9FB);color:var(--muted);padding:7px 10px;font-size:9.5px;font-weight:700;cursor:pointer}.funding-sector-tabs button.active{border-color:var(--accent-line,rgba(128,200,166,.35));background:var(--accent-soft,rgba(128,200,166,.1));color:var(--accent-ink,var(--green))}
.funding-analysis-grid{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(340px,.8fr);gap:10px}.funding-pane{min-width:0;border:1px solid var(--line);border-radius:12px;background:var(--panel2,#FCFAFC);padding:12px}.funding-pane-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px;margin-bottom:9px}.funding-pane-head b{color:var(--ink);font-size:11px}.funding-pane-head span{color:var(--soft);font-size:9px;text-align:right}.funding-quadrant{position:relative;min-height:330px;border:1px solid var(--line);border-radius:10px;background:var(--panel,#fff);overflow:hidden}.funding-quadrant svg{display:block;width:100%;height:330px}.funding-axis{stroke:rgba(91,47,100,.22);stroke-width:1}.funding-gridline{stroke:rgba(91,47,100,.08);stroke-width:1;stroke-dasharray:3 4}.funding-point{stroke:#fff;stroke-width:1.5;opacity:.88}.funding-point.q-hh{fill:#2E7D5B}.funding-point.q-lh{fill:#734A7E}.funding-point.q-hl{fill:#A9741A}.funding-point.q-ll{fill:#AC4238}.funding-point-label{fill:var(--muted);font:650 9px var(--sans)}.funding-quadrant-label{fill:var(--soft);font:650 9px var(--sans)}.funding-axis-label{fill:var(--muted);font:600 9px var(--sans)}
.funding-ranking-wrap{overflow:auto;max-height:330px}.funding-ranking{width:100%;border-collapse:collapse}.funding-ranking th{position:sticky;top:0;background:var(--panel2,#FCFAFC);z-index:1;padding:7px 6px;border-bottom:1px solid var(--line);color:var(--soft);font-size:9px;text-align:right}.funding-ranking th:nth-child(2),.funding-ranking td:nth-child(2){text-align:left}.funding-ranking td{padding:8px 6px;border-bottom:1px solid var(--line);color:var(--ink);font:650 9.5px var(--mono);text-align:right}.funding-ranking td:first-child{color:var(--soft)}.funding-ranking td:nth-child(2){font-family:var(--sans);font-weight:700}.funding-ranking tr:last-child td{border-bottom:0}.funding-growth.up{color:var(--green)}.funding-growth.down{color:var(--red)}.funding-empty{display:grid;place-items:center;min-height:230px;padding:20px;color:var(--muted);font-size:10px;line-height:1.6;text-align:center}.funding-coverage{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px;color:var(--soft);font-size:9px}.funding-coverage b{color:var(--ink)}.funding-caveat{margin-top:10px;padding:9px 10px;border:1px solid rgba(169,116,26,.16);border-radius:9px;background:rgba(169,116,26,.055);color:#806538;font-size:9.5px;line-height:1.55}.funding-caveat b{color:#6E531E}
@media(max-width:980px){.funding-analysis-grid{grid-template-columns:1fr}.funding-market-strip{grid-template-columns:repeat(3,minmax(180px,1fr));overflow:auto}.funding-market-card{min-width:180px}}@media(max-width:620px){.market-funding{padding:14px}.market-funding-head{flex-direction:column}.funding-market-strip{display:flex}.funding-market-card{flex:0 0 78vw}.funding-quadrant,.funding-quadrant svg{min-height:300px;height:300px}.funding-pane-head{flex-direction:column}.funding-pane-head span{text-align:left}}
</style>
"""

_JS = r"""
<script id="market-funding-strategy-script">
(()=>{
"use strict";
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const signed=(v,d=1)=>Number.isFinite(Number(v))?`${Number(v)>=0?"+":""}${Number(v).toFixed(d)}`:"—";
const trillion=v=>Number.isFinite(Number(v))?`${Number(v).toLocaleString("ko-KR",{maximumFractionDigits:2})}조`:`—`;
const data=(()=>{try{return JSON.parse($("rate-monitor-data")?.textContent||"{}")?.strategy?.market_funding||null}catch{return null}})();
if(!data||!data.available)return;
function marketCards(){const rows=data.market_flow||[];if(!rows.length)return '<div class="funding-empty">ECOS 업권 수신잔액 시계열이 아직 없습니다.</div>';return rows.map(x=>{const yoy=Number(x.yoy_pct),cls=Number.isFinite(yoy)?(yoy>0?"up":yoy<0?"down":""):"";return `<div class="funding-market-card"><span>${esc(x.label)} · ${esc(x.latest_month)}</span><b>${trillion(x.balance_trillion_krw)} <small>원</small></b><em class="${cls}">YoY ${Number.isFinite(yoy)?signed(yoy,1)+"%":"비교기간 없음"}</em></div>`}).join("")}
function sectors(){const order=["savings_bank","cu","nh_local"],labels=data.sector_labels||{};return order.filter(s=>(data.growth_rankings?.[s]||[]).length||data.coverage?.[s]).map(s=>({key:s,label:labels[s]||s}))}
function quadrantHtml(sector){const q=data.quadrant||{};if(sector!=="savings_bank")return '<div class="funding-empty">이 업권은 현재 기관별 금리 identity와 예수부채를 같은 기준으로 연결하지 않았습니다.<br>성장률 랭킹만 표시합니다.</div>';if(!q.available||!(q.items||[]).length)return `<div class="funding-empty">${esc(q.reason||"4분면 연결표본이 없습니다.")}</div>`;const items=q.items||[],W=720,H=330,pad={l:54,r:24,t:28,b:42};const xs=items.map(x=>Number(x.rate_vs_market_bp)).filter(Number.isFinite),ys=items.map(x=>Number(x.yoy_pct)).filter(Number.isFinite);const xAbs=Math.max(10,...xs.map(Math.abs)),yAbs=Math.max(5,...ys.map(Math.abs));const sx=x=>pad.l+(x+xAbs)/(2*xAbs)*(W-pad.l-pad.r),sy=y=>H-pad.b-(y+yAbs)/(2*yAbs)*(H-pad.t-pad.b),x0=sx(0),y0=sy(0);const sorted=[...items].sort((a,b)=>Math.abs(Number(b.yoy_pct))-Math.abs(Number(a.yoy_pct))),labelIds=new Set(sorted.slice(0,8).map(x=>x.institution_id));const points=items.map(x=>{const xp=sx(Number(x.rate_vs_market_bp)),yp=sy(Number(x.yoy_pct));const qc=Number(x.rate_vs_market_bp)>=0?(Number(x.yoy_pct)>=0?"q-hh":"q-hl"):(Number(x.yoy_pct)>=0?"q-lh":"q-ll");const label=labelIds.has(x.institution_id)?`<text class="funding-point-label" x="${xp+7}" y="${yp-6}">${esc(String(x.institution).slice(0,12))}</text>`:"";return `<g><circle class="funding-point ${qc}" cx="${xp}" cy="${yp}" r="5"><title>${esc(x.institution)} · 금리포지션 ${signed(x.rate_vs_market_bp,1)}bp · 예수부채 YoY ${signed(x.yoy_pct,1)}%</title></circle>${label}</g>`}).join("");return `<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="저축은행 금리 포지션과 예수부채 성장률 4분면"><line class="funding-gridline" x1="${pad.l}" x2="${W-pad.r}" y1="${sy(yAbs/2)}" y2="${sy(yAbs/2)}"/><line class="funding-gridline" x1="${pad.l}" x2="${W-pad.r}" y1="${sy(-yAbs/2)}" y2="${sy(-yAbs/2)}"/><line class="funding-gridline" y1="${pad.t}" y2="${H-pad.b}" x1="${sx(xAbs/2)}" x2="${sx(xAbs/2)}"/><line class="funding-gridline" y1="${pad.t}" y2="${H-pad.b}" x1="${sx(-xAbs/2)}" x2="${sx(-xAbs/2)}"/><line class="funding-axis" x1="${pad.l}" x2="${W-pad.r}" y1="${y0}" y2="${y0}"/><line class="funding-axis" y1="${pad.t}" y2="${H-pad.b}" x1="${x0}" x2="${x0}"/><text class="funding-quadrant-label" x="${x0+12}" y="${pad.t+13}">고금리 · 성장</text><text class="funding-quadrant-label" x="${pad.l+8}" y="${pad.t+13}">저금리 · 성장</text><text class="funding-quadrant-label" x="${x0+12}" y="${H-pad.b-9}">고금리 · 감소</text><text class="funding-quadrant-label" x="${pad.l+8}" y="${H-pad.b-9}">저금리 · 감소</text><text class="funding-axis-label" x="${W/2-100}" y="${H-12}">현재 12개월 최고금리 - 연결표본 중앙값 (bp)</text><text class="funding-axis-label" transform="rotate(-90 13 ${H/2})" x="13" y="${H/2}">예수부채 YoY (%)</text>${points}</svg>`}
function rankingHtml(sector){const rows=data.growth_rankings?.[sector]||[];if(!rows.length)return '<div class="funding-empty">verified identity + 전년 동월 관측을 모두 만족하는 기관이 아직 없습니다.</div>';return `<div class="funding-ranking-wrap"><table class="funding-ranking"><thead><tr><th>순위</th><th>기관</th><th>예수부채</th><th>YoY</th><th>업권 백분위</th></tr></thead><tbody>${rows.slice(0,20).map(x=>`<tr><td>${x.rank}</td><td>${esc(x.institution)}</td><td>${trillion(x.balance_trillion_krw)}</td><td class="funding-growth ${Number(x.yoy_pct)>=0?"up":"down"}">${signed(x.yoy_pct,1)}%</td><td>${Number(x.sector_percentile).toFixed(0)}</td></tr>`).join("")}</tbody></table></div>`}
function coverageHtml(sector){const c=data.coverage?.[sector];if(!c)return "";return `<div class="funding-coverage"><span>기준월 <b>${esc(c.latest_month)}</b></span><span>원천기관 <b>${c.institution_count}</b></span><span>identity 검증 <b>${c.verified_identity_count}</b></span><span>미검증 <b>${c.unverified_identity_count}</b></span></div>`}
function renderSector(sector){document.querySelectorAll("#funding-sector-tabs button").forEach(b=>b.classList.toggle("active",b.dataset.sector===sector));const label=data.sector_labels?.[sector]||sector;$("funding-quadrant-title").textContent=sector==="savings_bank"?"금리 포지션 × 예수부채 성장 4분면":`${label} 분석축`;$("funding-quadrant").innerHTML=quadrantHtml(sector);$("funding-ranking-title").textContent=`${label} 예수부채 성장률 랭킹`;$("funding-ranking-body").innerHTML=rankingHtml(sector)+coverageHtml(sector)}
function install(){if($("market-funding-competition"))return;const anchor=$("external-market-context")||$("market-intelligence")||$("market-flow");if(!anchor)return;const list=sectors(),initial=list.some(x=>x.key==="savings_bank")?"savings_bank":list[0]?.key;const section=document.createElement("section");section.id="market-funding-competition";section.className="card market-funding";section.innerHTML=`<div class="market-funding-head"><div><h2>수신시장 · 기관별 자금조달 경쟁</h2><p>업권 전체 잔액 흐름과 기관별 예수부채 성장, 현재 금리 포지션을 같은 화면에서 봅니다.</p></div><span class="market-funding-badge">D0 + verified D1</span></div><div class="funding-market-strip">${marketCards()}</div><div id="funding-sector-tabs" class="funding-sector-tabs">${list.map(x=>`<button type="button" data-sector="${x.key}">${esc(x.label)}</button>`).join("")}</div><div class="funding-analysis-grid"><div class="funding-pane"><div class="funding-pane-head"><b id="funding-quadrant-title">4분면</b><span>금리축은 현재 포지션 · 수신축은 YoY</span></div><div id="funding-quadrant" class="funding-quadrant"></div></div><div class="funding-pane"><div class="funding-pane-head"><b id="funding-ranking-title">성장률 랭킹</b><span>업권 내부 · verified identity</span></div><div id="funding-ranking-body"></div></div></div><div class="funding-caveat"><b>해석 주의</b> — 예수부채 증감은 순유입(net flow)이 아닙니다. 4분면은 현재 금리 포지션과 잔액 성장의 동시 관찰이며 금리 인상의 인과효과를 뜻하지 않습니다. 농협중앙회는 단위 농·축협 랭킹에서 제외합니다.</div>`;anchor.insertAdjacentElement("afterend",section);section.querySelectorAll("#funding-sector-tabs button").forEach(b=>b.addEventListener("click",()=>renderSector(b.dataset.sector)));if(initial)renderSector(initial)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install,{once:true});else install();
})();
</script>
"""


def inject_market_funding_strategy_presentation(html: str) -> str:
    """Strategy HTML에 수신시장 경쟁 분석 presentation을 한 번만 주입한다."""
    has_style = STYLE_MARKER in html
    has_script = SCRIPT_MARKER in html
    if has_style and has_script:
        return html
    if has_style != has_script:
        raise DashboardBuildError("Market Funding Strategy 주입 상태가 불완전하다")
    if "</head>" not in html or "</body>" not in html:
        raise DashboardBuildError("Market Funding Strategy 주입 위치를 찾지 못했다")
    if 'id="rate-monitor-data"' not in html or 'id="market-flow"' not in html:
        raise DashboardBuildError("Strategy 데이터/시장 DOM 계약을 찾지 못했다")
    rendered = html.replace("</head>", _CSS + "\n</head>", 1)
    return rendered.replace("</body>", _JS + "\n</body>", 1)
