# ruff: noqa: E501
"""Strategy 금리결정·시장근거 세부 refinement presentation.

기존 수집값·금리계산·inflow sensitivity 계수는 바꾸지 않는다. 이미 존재하는
시장/예측 read model을 의사결정 순서에 맞춰 더 명확하게 표시하고, 30일 상품변경
이벤트와 stable-product snapshot 비교처럼 서로 다른 Evidence 계약을 화면에서
구분한다.
"""

from __future__ import annotations

from rate_monitor.services.dashboard_service import DashboardBuildError

STYLE_MARKER = 'id="strategy-decision-evidence-refinement-style"'
SCRIPT_MARKER = 'id="strategy-decision-evidence-refinement-script"'

_CSS = r"""
<style id="strategy-decision-evidence-refinement-style">
/* 01 — 금리결정 surface 대비/가독성. */
.workspace-decision .planning-strip>div{border-color:rgba(91,47,100,.20)!important;background:linear-gradient(145deg,#fff,#f6edf5)!important;box-shadow:0 5px 16px rgba(77,45,88,.07)!important}
.workspace-decision .planning-strip span{color:#554159!important;font-size:12px!important;font-weight:700!important}.workspace-decision .planning-strip b{color:#2e1c32!important;font-size:19px!important;font-weight:820!important}.workspace-decision .planning-strip small{color:#655268!important;font-size:11.5px!important;line-height:1.5!important}
.workspace-decision .engine-summary{border-color:rgba(115,74,126,.24)!important;background:#f1e6f2!important;color:#57425b!important;font-size:12px!important;font-weight:680!important}
.workspace-decision .prediction-panel{gap:14px!important;padding:15px!important;border-color:rgba(91,47,100,.20)!important;background:#fff!important;box-shadow:0 8px 24px rgba(77,45,88,.06)!important}
.workspace-decision .prediction-explain{padding:13px 14px!important;border-color:rgba(79,111,159,.19)!important;background:#eef5fb!important}.workspace-decision .prediction-explain b{color:#264968!important;font-size:13.5px!important}.workspace-decision .prediction-explain p{color:#4c6578!important;font-size:12px!important;line-height:1.62!important}
.workspace-decision .prediction-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.workspace-decision .prediction-head b{color:#302035!important;font-size:16px!important}.workspace-decision .model-status{font-size:11.5px!important;padding:4px 7px;border:1px solid rgba(169,116,26,.22);border-radius:999px;background:#fff7e7;color:#7d581b}
.workspace-decision .predict-inputs{gap:10px!important}.workspace-decision .predict-inputs label{color:#4f3a53!important;font-size:12px!important;font-weight:720!important}.workspace-decision .predict-inputs input{margin-top:6px!important;min-height:42px!important;padding:9px 11px!important;border:1px solid rgba(91,47,100,.17)!important;border-radius:9px!important;font-size:14px!important}
.workspace-decision .prediction-results .simresult{border-color:rgba(91,47,100,.16)!important;background:#f9f5f9!important}.workspace-decision .prediction-results .simresult span{color:#57445b!important;font-size:12px!important}.workspace-decision .prediction-results .simresult b{font-size:17px!important}.workspace-decision .prediction-results .simresult small{color:#6c596f!important;font-size:11.5px!important}
.workspace-model-detail{border-color:rgba(91,47,100,.18)!important;background:#fff!important}.workspace-model-detail>summary{padding:12px 13px!important;color:#47334c!important;font-size:12px!important;background:#f6eef6!important}.workspace-model-detail-body{padding:0 12px 12px!important;gap:12px!important}

/* 수식 / 민감도 / 근거를 서로 다른 의미로 분리한다. */
.decision-formula,.decision-model-evidence{border:1px solid rgba(91,47,100,.13);border-radius:10px;overflow:hidden}.decision-formula{border-color:rgba(79,111,159,.17);background:#f5f9fd}.decision-model-evidence{background:#faf6fa}.decision-formula>summary,.decision-model-evidence>summary{cursor:pointer;list-style:none;padding:11px 12px;font-size:12px;font-weight:780}.decision-formula>summary{color:#2e587b}.decision-model-evidence>summary{color:#523c57}.decision-formula>summary::-webkit-details-marker,.decision-model-evidence>summary::-webkit-details-marker{display:none}.decision-formula>summary:after,.decision-model-evidence>summary:after{content:"펼치기";float:right;font-size:10.5px;font-weight:600;color:#77848e}.decision-formula[open]>summary:after,.decision-model-evidence[open]>summary:after{content:"접기"}
.decision-formula-body{display:grid;gap:8px;padding:0 12px 12px}.decision-formula-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.decision-formula-card{padding:10px 11px;border:1px solid rgba(79,111,159,.12);border-radius:9px;background:#fff}.decision-formula-card b{display:block;margin-bottom:4px;color:#2d485b;font-size:11.5px}.decision-formula-card code{display:block;color:#3a5162;font:650 11px/1.55 var(--mono);white-space:normal}.decision-formula-note{margin:0;color:#607584;font-size:11px;line-height:1.55}
.decision-model-evidence .model-evidence{margin:0!important;border:0!important;border-top:1px solid rgba(91,47,100,.09)!important;border-radius:0!important;background:#fff!important;padding:12px 13px!important}.decision-model-evidence .model-evidence>b{display:none}.decision-model-evidence .model-evidence span{color:#5e4d62!important;font-size:11.5px!important;line-height:1.62!important}
.decision-sensitivity{display:grid;gap:9px}.decision-sensitivity-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.decision-sensitivity-head b{color:#39273e;font-size:13px}.decision-sensitivity-head span{color:#725f75;font-size:11px}.decision-sensitivity-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.decision-sensitivity-card{padding:12px;border:1px solid rgba(91,47,100,.14);border-radius:10px;background:#fff}.decision-sensitivity-card.base{border-color:rgba(211,58,124,.27);background:#fff4f9}.decision-sensitivity-title{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:9px}.decision-sensitivity-title b{color:#36243b;font-size:13px}.decision-sensitivity-title span{color:#725f75;font-size:10.5px}.decision-sensitivity-total{display:block;color:#5b2f64;font-size:21px;font-weight:820;letter-spacing:-.035em}.decision-sensitivity-metrics{display:grid;gap:4px;margin-top:8px;color:#635067;font-size:11px}.decision-sensitivity-metrics div{display:flex;justify-content:space-between;gap:10px}.decision-sensitivity-metrics strong{color:#3d2b42}.decision-sensitivity-empty{padding:14px;border:1px dashed rgba(91,47,100,.18);border-radius:9px;background:#faf7fa;color:#6e5b72;font-size:11.5px;text-align:center}.decision-range-legacy{display:none!important}

/* 02 — 수신잔액을 주 근거, 신규취급 금리를 보조 anchor로 배치. */
.external-context .external-context-flows{margin-bottom:12px}.external-context .external-flow{padding:13px 12px!important;border-color:rgba(91,47,100,.15)!important;background:linear-gradient(145deg,#fff,#f6eff6)!important}.external-context .external-flow span{color:#554159!important;font-size:11.5px!important}.external-context .external-flow b{font-size:18px!important}.external-context .external-flow small{color:#655368!important;font-size:11px!important;line-height:1.5!important}.decision-external-heading{display:flex;align-items:flex-end;justify-content:space-between;gap:12px;margin:3px 1px 8px}.decision-external-heading b{color:#38263d;font-size:12.5px}.decision-external-heading span{color:#705f73;font-size:10.5px}.decision-external-heading.secondary{margin-top:10px}.external-context .external-context-rates{margin-bottom:0}.external-context .external-context-card{background:#faf7fa!important}.external-context .external-context-card span{font-size:11px!important}.external-context .external-context-card small{font-size:10.5px!important;line-height:1.48!important}.decision-external-explain{margin:8px 1px 0;color:#69586d;font-size:10.8px;line-height:1.55}

/* 이벤트 30D와 동일상품 snapshot 30D를 명시적으로 분리. */
.decision-evidence-basis{margin:8px 0 0;padding:8px 10px;border:1px solid rgba(79,111,159,.14);border-radius:8px;background:#f3f7fb;color:#506b7e;font-size:10.8px;line-height:1.5}.market-intel-breadth .decision-breadth-counts{color:#46344b;font-weight:720}.changes .decision-event-basis{margin:0 0 10px}.changes[open] summary:after{content:"항상 펼침"!important}.changes summary{cursor:default!important}

/* 작은 움직임을 읽기 위한 bp delta view. */
.decision-trend-toggle{display:flex;gap:5px;align-items:center;margin-left:auto}.decision-trend-toggle button{border:1px solid rgba(91,47,100,.13);border-radius:8px;background:#faf7fa;color:#655768;padding:5px 8px;font-size:10.5px;font-weight:700;cursor:pointer}.decision-trend-toggle button.active{border-color:var(--accent-line);background:var(--accent-soft);color:var(--accent-ink)}.decision-trend-basis{margin:4px 0 0;color:#6d5d70;font-size:10.5px}.trendline.delta-mean{stroke:#4e9675}.trendline.delta-max{stroke:#a9741a}.trendline.delta-own{stroke:#b34a77;stroke-dasharray:7 5}.trenddot.delta-mean{fill:#4e9675}.trenddot.delta-max{fill:#a9741a}.trenddot.delta-own{fill:#b34a77}.trendlabel.delta-mean{fill:#2e7d5b}.trendlabel.delta-max{fill:#96661d}.trendlabel.delta-own{fill:#a53e6d}

/* 01 IA: 준비도 → 인사이트 → 경쟁사 TOP5 → 시나리오. */
.decision-integrated-insight{margin:0 0 12px!important}.decision-integrated-insight .head h2{font-size:18px!important}.decision-integrated-insight .insights{grid-template-columns:repeat(2,minmax(0,1fr))!important}.decision-integrated-insight .insight{border-color:rgba(91,47,100,.13)!important;background:#faf7fa!important}.decision-integrated-top5{margin:0 0 12px!important}.decision-integrated-top5 .head h2{font-size:18px!important}.decision-integrated-top5 .tablewrap{overflow:auto}.workspace-insights[hidden],.workspace-detail[hidden],#workspace-label-detail[hidden],.ux-region-handoff[hidden]{display:none!important}

@media(max-width:900px){.decision-sensitivity-grid,.decision-formula-grid,.decision-integrated-insight .insights{grid-template-columns:1fr}.decision-external-heading{align-items:flex-start;flex-direction:column;gap:2px}}
@media(max-width:760px){.workspace-decision .planning-strip b{font-size:17px!important}.workspace-decision .prediction-head b{font-size:15px!important}.workspace-decision .predict-inputs input{font-size:14px!important}.decision-sensitivity-total{font-size:19px}.decision-sensitivity-metrics{font-size:11.5px}.decision-formula-card code{font-size:10.5px}}
</style>
""".strip()

_JS = r"""
<script id="strategy-decision-evidence-refinement-script">
(()=>{
  "use strict";
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const fmt=new Intl.NumberFormat("ko-KR",{maximumFractionDigits:1});
  const payload=()=>{try{return JSON.parse($("rate-monitor-data")?.textContent||"{}")}catch{return{}}};
  const input=id=>{const raw=$(id)?.value??"",v=Number(raw);return String(raw).trim()!==""&&Number.isFinite(v)?v:null};
  const textNumber=id=>{const m=String($(id)?.textContent||"").replace(/,/g,"").match(/-?\d+(?:\.\d+)?/);return m?Number(m[0]):null};
  const amount=v=>Number.isFinite(v)?`${fmt.format(v)}억원`:"—";
  const signedAmount=v=>Number.isFinite(v)?`${v>=0?"+":""}${fmt.format(v)}억원`:"—";
  const logistic=x=>{if(x>=0){const z=Math.exp(-x);return 1/(1+z)}const z=Math.exp(x);return z/(1+z)};
  const model=()=>payload().strategy?.inflow_prediction||null;
  const termMonths=()=>{const m=String($("planning-basis")?.textContent||"").match(/\d+/);return m?Number(m[0]):12};
  const proposedRate=()=>{const base=input("base-n"),bonus=input("bonus-n");return Number.isFinite(base)&&Number.isFinite(bonus)?base+bonus:null};

  function runScenario({baseline,maturity,rollover,ownRate,proposed,top10,term,scenario,config}){
    const step=Number(config.rate_step_percentage_point)||.10;
    const currentGap=ownRate-top10,proposedGap=proposed-top10,relativeChange=proposedGap-currentGap,rateSteps=relativeChange/step;
    const maxLog=Number(config.max_abs_new_money_log_effect)||1.5,rawLog=Number(scenario.new_money_log_change_per_10bp)*rateSteps,logEffect=Math.max(-maxLog,Math.min(maxLog,rawLog));
    const newMoney=baseline*Math.exp(logEffect),guard=config.rollover_probability_guardrail||{min:.001,max:.999},p0=rollover/100,anchor=Math.max(Number(guard.min)||.001,Math.min(Number(guard.max)||.999,p0));
    const rollLogit=Math.log(anchor/(1-anchor))+Number(scenario.rollover_log_odds_change_per_10bp)*rateSteps,p1=Math.abs(rateSteps)<=1e-12?p0:logistic(rollLogit),renewal=maturity*p1;
    const baselineTotal=baseline+maturity*p0,total=newMoney+renewal,delta=total-baselineTotal,termFactor=term/12,baselineCost=baselineTotal*ownRate/100*termFactor,predictedCost=total*proposed/100*termFactor;
    return{newMoney,p1,renewal,total,delta,cost:predictedCost-baselineCost,currentGap,proposedGap,relativeChange,rateSteps};
  }
  function predictAll(args){const config=model();if(!config)return null;const scenarios={};for(const s of config.scenarios||[])scenarios[s.key]=runScenario({...args,scenario:s,config});const base=scenarios.base||Object.values(scenarios)[0],totals=Object.values(scenarios).map(x=>x.total);return{base,scenarios,minTotal:Math.min(...totals),maxTotal:Math.max(...totals)}}
  function ensurePredictionBridge(){if(typeof window.predictInflow!=="function")window.predictInflow=args=>predictAll(args)}

  function formulaHtml(config){const coef=(config?.scenarios||[]).map(s=>`${esc(s.label)} β=${Number(s.new_money_log_change_per_10bp).toFixed(2)} / γ=${Number(s.rollover_log_odds_change_per_10bp).toFixed(2)}`).join(" · ");return`<details class="decision-formula" open><summary>계산 수식 · 숫자가 만들어지는 순서</summary><div class="decision-formula-body"><div class="decision-formula-grid"><div class="decision-formula-card"><b>① 상대금리 이동</b><code>rate_steps = (제안금리 − 현재 당사금리) ÷ 0.10%p</code></div><div class="decision-formula-card"><b>② 신규자금</b><code>신규자금 = 최근월 신규수신 × exp(clamp(β × rate_steps, −1.5, +1.5))</code></div><div class="decision-formula-card"><b>③ 재예치</b><code>logit(p1) = logit(현재 재예치율) + γ × rate_steps<br>재예치액 = 만기도래액 × p1</code></div><div class="decision-formula-card"><b>④ 총수신·비용</b><code>총수신 = 신규자금 + 재예치액<br>증감 = 총수신 − 현재금리 baseline 총수신<br>표면이자 = 총수신 × 금리 × 기간/12</code></div></div><p class="decision-formula-note"><b>민감도 계수:</b> ${coef||"모형 설정 확인 필요"}. β·γ는 외부 논문에서 가져온 검증계수가 아니라 내부 실적 미보정 스트레스 가정입니다.</p></div></details>`}

  function installPredictionDetails(){
    const detail=document.querySelector(".workspace-model-detail"),body=detail?.querySelector(".workspace-model-detail-body");if(!detail||!body)return;
    const summary=detail.querySelector(":scope>summary");if(summary&&summary.childNodes.length)summary.childNodes[0].textContent="예측모형 상세 · 계산 수식 / 민감도 / 근거 ";
    if(!body.querySelector(".decision-formula"))body.insertAdjacentHTML("afterbegin",formulaHtml(model()));
    const evidence=body.querySelector(".model-evidence");if(evidence&&!evidence.closest(".decision-model-evidence")){const wrapper=document.createElement("details");wrapper.className="decision-model-evidence";wrapper.innerHTML="<summary>모형 근거 · 외부 연구 / 가정 경계</summary>";evidence.parentNode.insertBefore(wrapper,evidence);wrapper.appendChild(evidence)}
    $("inflow-range")?.closest(".simresult")?.classList.add("decision-range-legacy");
    if(!body.querySelector(".decision-sensitivity")){const section=document.createElement("section");section.className="decision-sensitivity";section.innerHTML='<div class="decision-sensitivity-head"><div><b>민감도별 총수신 시나리오</b><span>같은 제안금리를 저민감·기준·고민감 계수로 각각 계산합니다.</span></div><span>미보정 stress</span></div><div class="decision-sensitivity-grid" id="decision-sensitivity-grid"></div>';body.querySelector(".decision-formula")?.insertAdjacentElement("afterend",section)}
    renderSensitivity();
  }
  function renderSensitivity(){const host=$("decision-sensitivity-grid"),config=model();if(!host||!config)return;const baseline=input("baseline-new"),maturity=input("maturity-amount"),rollover=input("rollover-rate"),ownRate=textNumber("own-max"),top10=textNumber("sim-top10"),proposed=proposedRate(),term=termMonths();if(![baseline,maturity,rollover,ownRate,top10,proposed].every(Number.isFinite)){host.innerHTML='<div class="decision-sensitivity-empty" style="grid-column:1/-1">최근 월 신규수신 기준액 · 다음 만기도래액 · 현재 재예치율과 시장/당사 금리가 준비되면 저·기준·고민감 결과를 각각 표시합니다.</div>';return}const result=predictAll({baseline,maturity,rollover,ownRate,proposed,top10,term});host.innerHTML=(config.scenarios||[]).map(s=>{const r=result.scenarios[s.key];return`<article class="decision-sensitivity-card ${s.key==="base"?"base":""}" data-sensitivity="${esc(s.key)}"><div class="decision-sensitivity-title"><b>${esc(s.label)}</b><span>β ${Number(s.new_money_log_change_per_10bp).toFixed(2)} · γ ${Number(s.rollover_log_odds_change_per_10bp).toFixed(2)}</span></div><strong class="decision-sensitivity-total">${amount(r.total)}</strong><div class="decision-sensitivity-metrics"><div><span>신규자금</span><strong>${amount(r.newMoney)}</strong></div><div><span>재예치</span><strong>${amount(r.renewal)} · ${(r.p1*100).toFixed(1)}%</strong></div><div><span>현재 대비</span><strong>${signedAmount(r.delta)}</strong></div><div><span>추가 표면이자비용</span><strong>${signedAmount(r.cost)}</strong></div></div></article>`}).join("")}

  function refineExternal(){const panel=$("external-market-context");if(!panel||panel.dataset.decisionRefined==="1")return;const market=payload().strategy?.external_features?.deposit_market||{},flows=panel.querySelector(".external-context-flows"),rates=panel.querySelector(".external-context-rates"),head=panel.querySelector(".external-context-head");if(!flows||!rates||!head)return;const months=Object.values(market.sector_balances||{}).map(x=>x?.data_month).filter(Boolean).sort(),latest=months.at(-1)||"기준월 미확인";const flowHead=document.createElement("div");flowHead.className="decision-external-heading";flowHead.innerHTML=`<b>업권 수신잔액 흐름</b><span>공식 월간통계 최신 공표월 ${esc(latest)} · ECOS 공표시차 반영</span>`;head.insertAdjacentElement("afterend",flowHead);flowHead.insertAdjacentElement("afterend",flows);const rateHead=document.createElement("div");rateHead.className="decision-external-heading secondary";rateHead.innerHTML='<b>보조 금리환경</b><span>예금은행권 신규취급액 가중평균 · 공시상품 단순평균 아님</span>';flows.insertAdjacentElement("afterend",rateHead);rateHead.insertAdjacentElement("afterend",rates);const cards=rates.querySelectorAll(".external-context-card");if(cards[1]){cards[1].querySelector("span").textContent="예금은행 순수저축성예금 신규취급액 가중평균";const small=cards[1].querySelector("small");if(small)small.innerHTML+=`<br>해당 월 새로 취급된 금액 기준`}if(cards[2]){cards[2].querySelector("span").textContent="예금은행 1년 정기예금 신규취급액 가중평균";const small=cards[2].querySelector("small");if(small)small.innerHTML+=`<br>12개월 시장가격 보조 anchor`}const copy=panel.querySelector(".external-context-head p");if(copy)copy.textContent="업권별 월말 수신잔액 증감을 먼저 보고, 기준금리와 예금은행 신규취급 가중평균금리는 보조 환경으로 확인합니다.";const explain=document.createElement("p");explain.className="decision-external-explain";explain.textContent=`최신 월은 원천 ECOS가 공표한 값까지만 표시합니다(${latest}). 아직 공표되지 않은 월을 추정·보간하지 않습니다.`;rates.insertAdjacentElement("afterend",explain);panel.dataset.decisionRefined="1"}

  function activeMarketIntelScope(){const panel=$("market-intelligence"),intel=payload().strategy?.market_intelligence;if(!panel||!intel)return null;const sector=panel.querySelector("[data-mi-sector].active")?.dataset.miSector||"savings_bank",term=Number(panel.querySelector("[data-mi-term].active")?.dataset.miTerm||12),windowDays=Number(panel.querySelector("[data-mi-window].active")?.dataset.miWindow||30);return intel.scopes?.find(x=>x.sector===sector&&Number(x.term_months)===term&&Number(x.window_days)===windowDays)||null}
  let marketRefining=false;
  function refineMarketIntel(){if(marketRefining)return;const panel=$("market-intelligence"),body=$("market-intelligence-body");if(!panel||!body)return;marketRefining=true;try{const desired="동일 stable product의 시작/종료 snapshot을 비교합니다. 아래 30일 상품변경 이벤트 집계와는 별도 Evidence입니다.",copy=panel.querySelector(".market-intel-head p");if(copy&&copy.textContent!==desired)copy.textContent=desired;const item=activeMarketIntelScope(),breadth=body.querySelector(".market-intel-breadth span:last-child");if(item?.status==="supported"&&breadth){const text=`인상 ${Number(item.up_count||0).toLocaleString("ko-KR")}건 · 인하 ${Number(item.down_count||0).toLocaleString("ko-KR")}건 · 이동없음 ${Number(item.unchanged_count||0).toLocaleString("ko-KR")}건 · 총 ${Number(item.comparable_product_count||0).toLocaleString("ko-KR")}건 · 상위 10% 구성 교체율 ${(Number(item.top_decile_churn_rate||0)*100).toFixed(0)}%`;breadth.classList.add("decision-breadth-counts");if(breadth.textContent!==text)breadth.textContent=text}if(!body.querySelector(".decision-evidence-basis")){const note=document.createElement("div");note.className="decision-evidence-basis";note.textContent=item?.status==="supported"?"근거: 요청기간에 대응하는 시작·종료 snapshot에서 동일 상품을 매칭해 비교합니다. 인상/인하/이동없음은 이 비교상품 집합의 건수입니다.":"근거: 이 카드는 동일상품 시작·종료 snapshot이 필요합니다. 최근 30일 상품변경 이벤트가 있어도 30D 시작 baseline snapshot이 부족하면 이 카드는 ‘비교 이력 부족’이 될 수 있습니다.";body.appendChild(note)}}finally{queueMicrotask(()=>{marketRefining=false})}}

  function keepChangesOpen(){const details=document.querySelector("#market-flow details.changes");if(!details)return;details.open=true;const summary=details.querySelector("summary");if(summary&&summary.dataset.decisionTitle!=="1"){const chip=summary.querySelector(".chip");if(summary.childNodes.length)summary.childNodes[0].textContent="최근 30일 상품변경 이벤트 · 방향과 주요 이벤트 ";if(chip)summary.appendChild(chip);summary.dataset.decisionTitle="1"}const body=details.querySelector(".changes-body");if(body&&!body.querySelector(".decision-event-basis")){const note=document.createElement("div");note.className="decision-evidence-basis decision-event-basis";note.textContent="근거: 최근 30일에 실제 발생한 상품 최고금리 변경 이벤트를 집계합니다. 동일상품의 30D 시작·종료 snapshot 비교와는 별도 지표입니다.";body.prepend(note)}if(details.dataset.decisionOpen!=="1"){details.addEventListener("toggle",()=>{if(!details.open)details.open=true});details.dataset.decisionOpen="1"}}

  const trendState={mode:"delta"};
  function drawTrend(){const grid=$("trend-grid"),series=$("trend-series"),chart=$("trend-chart"),tr=payload().strategy?.rate_trend||{};if(!grid||!series||!chart)return;const pts=(tr.points||[]).filter(x=>Number.isFinite(Number(x.mean_max_rate))&&Number.isFinite(Number(x.market_max_rate)));if(!pts.length)return;const fields=[{key:"mean_max_rate",klass:"delta-mean"},{key:"market_max_rate",klass:"delta-max"},{key:"our_company_max_rate",klass:"delta-own"}],bases={};for(const f of fields){const first=pts.find(p=>Number.isFinite(Number(p[f.key])));bases[f.key]=first?Number(first[f.key]):null}const convert=(v,key)=>trendState.mode==="delta"?(v-bases[key])*100:v,values=pts.flatMap(p=>fields.map(f=>Number.isFinite(Number(p[f.key]))&&Number.isFinite(bases[f.key])?convert(Number(p[f.key]),f.key):null).filter(Number.isFinite));if(!values.length)return;let lo=Math.min(...values),hi=Math.max(...values);if(trendState.mode==="delta"){lo=Math.min(lo,0);hi=Math.max(hi,0)}const span=Math.max(trendState.mode==="delta"?2:.04,hi-lo),pad=span*.18;let min=lo-pad,max=hi+pad;if(max<=min){min-=1;max+=1}const x0=72,x1=970,y0=22,y1=230,sx=i=>pts.length===1?(x0+x1)/2:x0+(x1-x0)*i/(pts.length-1),sy=v=>y1-(v-min)/(max-min)*(y1-y0),axis=v=>trendState.mode==="delta"?`${v>0?"+":""}${v.toFixed(1)}bp`:`${v.toFixed(2)}%`;grid.innerHTML=[0,.25,.5,.75,1].map(q=>{const y=y0+(y1-y0)*q,v=max-(max-min)*q;return`<line class="gridline" x1="${x0}" y1="${y}" x2="${x1}" y2="${y}"/><text class="axistext" x="8" y="${y+3}">${axis(v)}</text>`}).join("");let html="";for(const f of fields){const points=pts.map((p,i)=>{const raw=Number(p[f.key]);return Number.isFinite(raw)&&Number.isFinite(bases[f.key])?{x:sx(i),value:convert(raw,f.key)}:null}).filter(Boolean);if(!points.length)continue;html+=`<path data-decision-trend="1" class="trendline ${f.klass}" d="${points.map((p,i)=>`${i?"L":"M"}${p.x.toFixed(1)},${sy(p.value).toFixed(1)}`).join(" ")}"/>`;html+=points.map(p=>`<circle data-decision-trend="1" class="trenddot ${f.klass}" cx="${p.x}" cy="${sy(p.value)}" r="3.8"/>`).join("");const last=points.at(-1);html+=`<text data-decision-trend="1" class="trendlabel ${f.klass}" x="${last.x}" y="${Math.max(12,sy(last.value)-9)}" text-anchor="end">${axis(last.value)}</text>`}html+=pts.map((p,i)=>{const d=new Date(`${p.date}T00:00:00`),label=Number.isNaN(d.getTime())?p.date:`${String(d.getMonth()+1).padStart(2,"0")}/${String(d.getDate()).padStart(2,"0")}`;return`<text data-decision-trend="1" class="trenddate" x="${sx(i)}" y="257" text-anchor="middle">${label}</text>`}).join("");series.innerHTML=html;chart.setAttribute("aria-label",trendState.mode==="delta"?"시장 최고, 시장 평균, 고려저축은행 금리의 기준일 대비 변화 bp 추이":"시장 최고, 시장 평균, 고려저축은행 절대 금리 수준 추이");const note=$("decision-trend-basis");if(note)note.textContent=trendState.mode==="delta"?"각 선의 첫 관측값을 0bp로 두고 이후 변화폭만 확대해 표시합니다. 절대 금리 차이는 ‘금리수준’에서 확인합니다.":"실제 절대 금리 수준(%)을 동일 축에 표시합니다."}
  function installTrend(){const chart=$("trend-chart"),card=chart?.closest(".chartcard"),head=card?.querySelector(".head");if(!card||!head)return;if(!$("decision-trend-toggle")){const controls=document.createElement("div");controls.id="decision-trend-toggle";controls.className="decision-trend-toggle";controls.innerHTML='<button type="button" data-trend-mode="delta" class="active">기준일 대비 변화(bp)</button><button type="button" data-trend-mode="level">금리수준</button>';head.appendChild(controls);const note=document.createElement("p");note.id="decision-trend-basis";note.className="decision-trend-basis";card.querySelector(".chartlegend")?.insertAdjacentElement("afterend",note);controls.addEventListener("click",e=>{const button=e.target.closest("button[data-trend-mode]");if(!button)return;trendState.mode=button.dataset.trendMode;controls.querySelectorAll("button").forEach(x=>x.classList.toggle("active",x===button));drawTrend()})}const series=$("trend-series");if(series&&series.dataset.decisionObserver!=="1"){new MutationObserver(()=>{if(!series.querySelector('[data-decision-trend="1"]'))queueMicrotask(drawTrend)}).observe(series,{childList:true,subtree:true});series.dataset.decisionObserver="1"}setTimeout(drawTrend,0)}

  function integrateDecisionIA(){const readiness=document.querySelector(".ux-decision-readiness"),planning=$("planning-zone"),interpretation=document.querySelector(".workspace-insights"),insight=interpretation?.querySelector(".insightcard"),top5=document.querySelector(".top5-card"),primary=document.querySelector(".workspace-detail.primary"),labelProduct=$("workspace-label-product"),labelDetail=$("workspace-label-detail"),handoff=document.querySelector(".ux-region-handoff");if(!readiness||!planning)return;if(insight){insight.classList.add("decision-integrated-insight");const title=insight.querySelector(".head h2"),copy=insight.querySelector(".head p");if(title)title.textContent="금리결정 인사이트";if(copy)copy.textContent="금리결정 준비도에 없는 경쟁강도·지역차·우대조건 신호만 남겨 의사결정에 연결합니다.";readiness.insertAdjacentElement("afterend",insight);const host=insight.querySelector("#insights");if(host&&host.dataset.decisionDedupe!=="1"){const trim=()=>host.querySelectorAll(".insight").forEach(node=>{const tag=node.querySelector("em")?.textContent?.trim();if(tag==="저축은행 시장 방향"||tag==="당사 위치")node.remove()});new MutationObserver(trim).observe(host,{childList:true,subtree:true});trim();host.dataset.decisionDedupe="1"}}if(top5){top5.classList.add("decision-integrated-top5");(insight||readiness).insertAdjacentElement("afterend",top5)}if(interpretation)interpretation.hidden=true;if(primary)primary.hidden=true;if(labelDetail)labelDetail.hidden=true;if(handoff)handoff.hidden=true;const pref=$("preference-intelligence");if(labelProduct&&pref){labelProduct.querySelector("strong").textContent="상품·우대조건 설계";labelProduct.querySelector("span").textContent="시장 우대조건 침투율과 당사 조건을 상품 설계 관점에서 비교합니다.";pref.parentNode.insertBefore(labelProduct,pref)}}

  function bindPrediction(){["baseline-new","maturity-amount","rollover-rate","base-n","bonus-n","base-r","bonus-r"].forEach(id=>inputNode(id)?.addEventListener("input",renderSensitivity));document.querySelectorAll(".segment button").forEach(b=>b.addEventListener("click",()=>setTimeout(renderSensitivity,0)));const observer=new MutationObserver(()=>renderSensitivity());[$("own-max"),$("sim-top10"),$("planning-basis")].filter(Boolean).forEach(el=>observer.observe(el,{childList:true,subtree:true,characterData:true}))}
  function inputNode(id){return $(id)}
  function install(){if(document.documentElement.dataset.strategyDecisionEvidenceRefinement==="v1")return;ensurePredictionBridge();installPredictionDetails();bindPrediction();refineExternal();refineMarketIntel();keepChangesOpen();installTrend();integrateDecisionIA();const marketBody=$("market-intelligence-body");if(marketBody)new MutationObserver(()=>refineMarketIntel()).observe(marketBody,{childList:true,subtree:true});document.documentElement.dataset.strategyDecisionEvidenceRefinement="v1"}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install,{once:true});else install();
})();
</script>
""".strip()


def inject_strategy_decision_evidence_refinement(html: str) -> str:
    """Apply final decision/evidence readability and IA refinement."""
    has_style = STYLE_MARKER in html
    has_script = SCRIPT_MARKER in html
    if has_style and has_script:
        return html
    if has_style != has_script:
        raise DashboardBuildError("Strategy Decision Evidence refinement 주입 상태가 불완전하다")
    required = (
        'id="strategy-workspace-style"',
        'id="strategy-ux-refinement-style"',
        'id="strategy-readability-preference-v2-style"',
        'id="prediction-panel"',
        'id="market-flow"',
    )
    if any(marker not in html for marker in required):
        raise DashboardBuildError("Strategy Decision Evidence refinement 선행 계약을 찾지 못했다")
    if "</head>" not in html or "</body>" not in html:
        raise DashboardBuildError("Strategy Decision Evidence refinement 주입 위치를 찾지 못했다")
    rendered = html.replace("</head>", _CSS + "\n</head>", 1)
    return rendered.replace("</body>", _JS + "\n</body>", 1)
