"""참고지표 시계열 표 (v4 §7.1)

기준금리를 금융상품으로 저장하지 않는다. `rate_observations`에 넣으면
기관·상품·가입기간 칸이 전부 비고 화면의 비교표에도 섞여 든다. 기준금리는
비교 대상이 아니라 옆에 놓고 보는 값이다.

`UNIQUE(indicator_code, source_effective_at, source_id)`가 핵심이다.
하루 1회 수집하는데 값은 몇 달씩 같으므로, 이게 없으면 안 바뀐 값이 매일
한 줄씩 쌓인다 (§7.3).

표를 더하기만 한다. 기존 데이터는 건드리지 않는다.

원래 제목: market_indicators

Revision ID: 0a09e1fc2d26
Revises: d5a71c3f8b62
Create Date: 2026-08-06 11:48:42.723169
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import rate_monitor.db.types


revision: str = '0a09e1fc2d26'
down_revision: str | None = 'd5a71c3f8b62'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_indicators',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('indicator_code', sa.String(length=64), nullable=False),
    sa.Column('indicator_name', sa.String(length=128), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('source_effective_at', sa.Date(), nullable=True),
    sa.Column('value', rate_monitor.db.types.Rate(length=8), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('raw_artifact_id', sa.String(length=36), nullable=False),
    sa.Column('source_locator', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=80), nullable=False),
    sa.Column('validation_status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['raw_artifact_id'], ['raw_artifacts.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_code', 'source_effective_at', 'source_id', name='uq_market_indicators_point')
    )
    with op.batch_alter_table('market_indicators', schema=None) as batch_op:
        batch_op.create_index('ix_market_indicators_code', ['indicator_code', 'source_effective_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_indicators', schema=None) as batch_op:
        batch_op.drop_index('ix_market_indicators_code')

    op.drop_table('market_indicators')
    # ### end Alembic commands ###
