"""initial schema

Revision ID: bbb8671679bf
Revises: 
Create Date: 2026-08-05 07:06:30.849760
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import rate_monitor.db.types

revision: str = 'bbb8671679bf'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sector', sa.String(length=32), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('institution_type', sa.String(length=32), nullable=True),
    sa.Column('sido_code', sa.String(length=16), nullable=True),
    sa.Column('sigungu_code', sa.String(length=16), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('availability_scope', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institutions_normalized_name'), ['normalized_name'], unique=False)

    op.create_table('manual_overrides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=24), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=True),
    sa.Column('original_value_json', sa.JSON(), nullable=True),
    sa.Column('override_value_json', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('conflict_status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sector', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('source_role', sa.String(length=32), nullable=False),
    sa.Column('trust_level', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('base_reference', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_cron', sa.String(length=64), nullable=True),
    sa.Column('policy_status', sa.String(length=16), nullable=False),
    sa.Column('coverage_status', sa.String(length=16), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('query_context_json', sa.JSON(), nullable=False),
    sa.Column('raw_count', sa.Integer(), nullable=False),
    sa.Column('parsed_count', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('schema_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('previous_run_id', sa.String(length=36), nullable=True),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('blocked_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['previous_run_id'], ['collection_runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=16), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('normalized_alias', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_aliases_normalized_alias'), ['normalized_alias'], unique=False)

    op.create_table('outlets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('outlet_type', sa.String(length=16), nullable=False),
    sa.Column('sido_code', sa.String(length=16), nullable=True),
    sa.Column('sigungu_code', sa.String(length=16), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('product_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('is_special_sale', sa.Boolean(), nullable=False),
    sa.Column('sale_start', sa.Date(), nullable=True),
    sa.Column('sale_end', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_normalized_name'), ['normalized_name'], unique=False)

    op.create_table('source_entity_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=16), nullable=False),
    sa.Column('source_entity_key', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('source_payload_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('match_method', sa.String(length=32), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_entity_links', schema=None) as batch_op:
        batch_op.create_index('uq_source_entity_links_active', ['source_id', 'entity_type', 'source_entity_key'], unique=True, sqlite_where=sa.text('valid_to IS NULL'))

    op.create_table('product_variants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('outlet_id', sa.String(length=36), nullable=True),
    sa.Column('term_months', sa.Integer(), nullable=True),
    sa.Column('term_days', sa.Integer(), nullable=True),
    sa.Column('join_channel', sa.String(length=16), nullable=False),
    sa.Column('interest_method', sa.String(length=16), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=True),
    sa.Column('amount_min', sa.Integer(), nullable=True),
    sa.Column('amount_max', sa.Integer(), nullable=True),
    sa.Column('customer_scope', sa.Text(), nullable=True),
    sa.Column('rate_scope', sa.String(length=32), nullable=False),
    sa.Column('variant_key', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_key', name='uq_product_variants_key')
    )
    op.create_table('raw_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_type', sa.String(length=16), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content_length', sa.Integer(), nullable=False),
    sa.Column('encoding', sa.String(length=32), nullable=True),
    sa.Column('request_meta_json', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['collection_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'sha256', name='uq_raw_artifacts_run_sha')
    )
    op.create_table('review_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=24), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('issue_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['collection_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('variant_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('raw_artifact_id', sa.String(length=36), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('base_rate', rate_monitor.db.types.Rate(length=16), nullable=True),
    sa.Column('max_rate', rate_monitor.db.types.Rate(length=16), nullable=True),
    sa.Column('rate_basis', sa.String(length=32), nullable=False),
    sa.Column('source_detail_json', sa.JSON(), nullable=False),
    sa.Column('raw_preference_text', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=16), nullable=False),
    sa.Column('validation_message', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=80), nullable=False),
    sa.Column('base_source_locator', sa.Text(), nullable=False),
    sa.Column('option_source_locator', sa.Text(), nullable=True),
    sa.Column('source_record_hash', sa.String(length=80), nullable=False),
    sa.Column('source_effective_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['raw_artifact_id'], ['raw_artifacts.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['collection_runs.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'run_id', name='uq_rate_observations_variant_run')
    )
    op.create_table('preference_conditions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('observation_id', sa.String(length=36), nullable=False),
    sa.Column('condition_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('add_rate', rate_monitor.db.types.Rate(length=16), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=True),
    sa.Column('stackable', sa.Boolean(), nullable=True),
    sa.Column('parser_confidence', sa.Float(), nullable=True),
    sa.Column('parse_status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['rate_observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preference_conditions')
    op.drop_table('rate_observations')
    op.drop_table('review_items')
    op.drop_table('raw_artifacts')
    op.drop_table('product_variants')
    with op.batch_alter_table('source_entity_links', schema=None) as batch_op:
        batch_op.drop_index('uq_source_entity_links_active', sqlite_where=sa.text('valid_to IS NULL'))

    op.drop_table('source_entity_links')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_normalized_name'))

    op.drop_table('products')
    op.drop_table('outlets')
    with op.batch_alter_table('entity_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_aliases_normalized_alias'))

    op.drop_table('entity_aliases')
    op.drop_table('collection_runs')
    op.drop_table('sources')
    op.drop_table('manual_overrides')
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institutions_normalized_name'))

    op.drop_table('institutions')
    # ### end Alembic commands ###
